apiVersion: v1
kind: Service
metadata:
  name: serving-api
  namespace: mlops
  labels:
    app: serving-api
spec:
  type: NodePort
  selector:
    app: serving-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
  # Enable proxy redirection for MLflow
  sessionAffinity: None
