apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serving-models-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
